runtime:  python27
api_version: 1

handlers:
- url: /static
  static_dir: static
  secure: always

- url: /(.+)/
  static_files: static/\1/index.html
  upload: static/(.+)/index.html
- url: /(.*\.(bmp|gif|ico|jpeg|jpg|png))
  static_files: static/\1
  upload: static/(.*\.(bmp|gif|ico|jpeg|jpg|png))
