runtime:  python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: index.html
  upload: index.html
  secure: always
- url: /static
  static_dir: static
  secure: always
- url: /(.+)/
  static_files: index.html
  upload: index.html
  secure: always
- url: /(.*\.(bmp|gif|ico|jpeg|jpg|png))
  static_files: static/\1
  upload: static/(.*\.(bmp|gif|ico|jpeg|jpg|png))
  secure: always
- url: /(.*\.css)
  mime_type: text/css
  static_files: static/\1
  upload: static/(.*\.css)
  secure: always
- url: /(.*\.txt)
  mime_type: text/plain
  static_files: static/\1
  upload: static/(.*\.txt)
  secure: always
- url: /.well_known/acme-challenge/qf0b_wouOENKJxCGP_ZaPH2gyozpnPQHMAsZ_ZZpSS8
  mime_type: text/plain
  static_files: static/.well_known/acme-challenge/qf0b_wouOENKJxCGP_ZaPH2gyozpnPQHMAsZ_ZZpSS8
  upload: static/.well_known/acme-challenge/qf0b_wouOENKJxCGP_ZaPH2gyozpnPQHMAsZ_ZZpSS8
