runtime:  python27
api_version: 1
threadsafe: true

default_expiration: "4d"



handlers:
- url: /
  static_files: static/index.html
  upload: static/index.html
  secure: always
- url: /(.*)
  static_files: static/\1
  upload: st
  secure: always
