runtime:  python27
api_version: 1

handlers:
- url: /static
  static_dir: static
  secure: always
- url: /favicon.ico
  static_files: static/favicon/favicon.ico
  upload: static/favicon/favicon.ico
  secure: always
- url: /
  static_files: index.html
  upload: index.html
  secure: always
  
