runtime:  python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: index.html
  upload: index.html
  secure: always
- url: /static
  static_dir: static
- url: /(.+)/
  static_files: index.html
  upload: index.html
- url: /(.*\.(bmp|gif|ico|jpeg|jpg|png))
  static_files: static/\1
  upload: static/(.*\.(bmp|gif|ico|jpeg|jpg|png))
- url: /(.*\.css)
  mime_type: text/css
  static_files: static/\1
  upload: static/(.*\.css)
- url: /favicon.ico
  static_files: static/favicon/favicon.ico
  upload: static/favicon/favicon.ico
  secure: always