runtime:  python27
api_version: 1

handlers:
- url: /
  static_files: static/index.html
  upload: index.html
- url: /(.+)/
  static_files: static/\1/index.html
  upload: static/(.+)/index.html
- url: /(.*\.(bmp|gif|ico|jpeg|jpg|png))
  static_files: static/\1
  upload: static/(.*\.(bmp|gif|ico|jpeg|jpg|png))
- url: /(.*\.html)
  mime_type: text/html
  static_files: static/\1
  upload: static/(.*\.html)
- url: /(.*\.css)
  mime_type: text/css
  static_files: static/\1
  upload: static/(.*\.css)
- url: /favicon.ico
  static_files: static/favicon/favicon.ico
  upload: static/favicon/favicon.ico
  secure: always